# Generated by Django 4.2.6 on 2023-10-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
